version: 2.1


orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

workflows:
  sample: 
    jobs:
      - build-and-test
