version: 2.1


orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout
      - run:
          name: "Enforce Go Formatted Code"
          command: "! go fmt ./... 2>&1 | read"

workflows:
  sample: 
    jobs:
      - build-and-test
